# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test_ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  display:
  runs-on: ubuntu-latest
  env:
    platform: Azure
    region: central
    profile_path: profile/

    steps:
      -name: Display custom environment variables
        if: ${{ env.platform == 'Central' }}
        run: |
          echo "The platform is ${{ env.platform' }}
          echo "The region is $region"

